version: "3.7"
services:
  price-api:
    image: price-api
    networks:
      - backend
    ports:
      - "8081:3000"
    volumes:
      - my-named-shared-data:/contains_your_price_data
volumes:
  my-named-shared-data:
    external: "true"
networks:
  backend:
    driver: bridge